#!/usr/bin/env bash
# Auto-generate specs/INDEX.md from codebase analysis
# This script scans the codebase structure and generates keyword suggestions

set -e

OUTPUT_FILE="specs/INDEX.md"
TEMP_FILE=$(mktemp)

# Ensure specs directory exists
mkdir -p specs

# Function to extract keywords from directory and file names
generate_keywords() {
  local dir="$1"
  local keywords=""
  
  # Extract unique words from filenames (bash, sh, js, md, etc.)
  if [[ -d "$dir" ]]; then
    keywords=$(find "$dir" -type f -not -path "*/node_modules/*" -not -path "*/.git/*" 2>/dev/null | \
      xargs -I {} basename {} | \
      sed 's/[._-]/ /g' | \
      tr '[:upper:]' '[:lower:]' | \
      tr ' ' '\n' | \
      grep -v -E '^(sh|js|md|json|yaml|yml|txt|log|ps1|cmd|example|backup[0-9]*)$' | \
      sort | uniq | head -n 20 | tr '\n' ', ' | sed 's/,$//')
  fi
  
  echo "$keywords"
}

# Function to get file list for a module
get_file_list() {
  local pattern="$1"
  find . -type f -path "$pattern" -not -path "*/node_modules/*" -not -path "*/.git/*" 2>/dev/null | \
    sed 's|^\./||' | sort
}

# Start building the index
cat > "$TEMP_FILE" << 'EOF'
# The Pin - Ralph Discovery Index

This index helps AI agents discover existing functionality before implementing duplicates.

## Format

Each module entry includes:
- **Module Name**: Clear identifier for the functionality
- **Keywords**: Synonyms, library names, related terms (10-20 per module)
- **File Paths**: Where to find the implementation
- **Spec Link** (optional): Link to detailed specification

## Modules

EOF

# Analyze major directories and generate module entries
if [[ -d "lib" ]]; then
  cat >> "$TEMP_FILE" << EOF
### Common Libraries
**Keywords**: $(generate_keywords "lib"), shared functions, utility library, bash utilities, helper functions, common code, reusable functions

**File Paths**:
$(get_file_list "./lib/*.sh" | sed 's/^/- /')

**Spec Link**: N/A

---

EOF
fi

if [[ -d "system_instructions" ]]; then
  cat >> "$TEMP_FILE" << EOF
### Agent System Instructions
**Keywords**: $(generate_keywords "system_instructions"), agent instructions, system prompts, ai instructions, agent behavior, execution rules, agent configuration

**File Paths**:
$(get_file_list "./system_instructions/*.md" | sed 's/^/- /')

**Spec Link**: N/A

---

EOF
fi

if [[ -d "skills" ]]; then
  cat >> "$TEMP_FILE" << EOF
### Skills
**Keywords**: $(generate_keywords "skills"), agent skills, task skills, specialized functions, skill execution, skill library

**File Paths**:
$(get_file_list "./skills/**/*" | sed 's/^/- /')

**Spec Link**: N/A

---

EOF
fi

if [[ -d "scripts" ]]; then
  cat >> "$TEMP_FILE" << EOF
### Scripts
**Keywords**: $(generate_keywords "scripts"), automation scripts, utility scripts, helper scripts, build scripts, setup scripts

**File Paths**:
$(get_file_list "./scripts/*.sh" | sed 's/^/- /')

**Spec Link**: N/A

---

EOF
fi

if [[ -f "ralph.sh" ]]; then
  cat >> "$TEMP_FILE" << EOF
### Ralph Core
**Keywords**: ralph loop, agent loop, main executor, autonomous execution, iteration management, task orchestration

**File Paths**:
- ralph.sh
- agent.yaml
$(get_file_list "./*.sh" | grep -v ralph.sh | sed 's/^/- /' || true)

**Spec Link**: See README.md

---

EOF
fi

if [[ -d "specs" ]]; then
  cat >> "$TEMP_FILE" << EOF
### Specifications
**Keywords**: $(generate_keywords "specs"), spec documents, technical specs, design documents, architecture docs

**File Paths**:
$(get_file_list "./specs/*.md" | grep -v INDEX.md | sed 's/^/- /' || true)

**Spec Link**: N/A

---

EOF
fi

# Add usage guidelines
cat >> "$TEMP_FILE" << 'EOF'

## Usage Guidelines

1. **Before implementing new functionality**: Search this index for related keywords
2. **Found a match?**: Read the referenced files and specs
3. **No match?**: Implement the feature and add it to this index
4. **Updating the index**: Run `scripts/generate-pin.sh` or update manually

## Maintenance

This index should be updated when:
- New major functionality is added
- Existing modules are significantly refactored
- Keywords need refinement based on discovery patterns

**Auto-generated**: This file was generated by scripts/generate-pin.sh
**Manual refinement recommended**: Review keywords and add domain-specific terms
EOF

# Only update if different or doesn't exist
if [[ ! -f "$OUTPUT_FILE" ]] || ! diff -q "$TEMP_FILE" "$OUTPUT_FILE" > /dev/null 2>&1; then
  cp "$TEMP_FILE" "$OUTPUT_FILE"
  echo "Generated $OUTPUT_FILE"
  echo "Note: Review and refine keywords manually for better discoverability"
else
  echo "$OUTPUT_FILE is up to date"
fi

# Clean up
rm -f "$TEMP_FILE"
